version: '3'                                    # 指定 docker-compose.yml 文件的写法格式
services:                                       # 多个容器集合
  node_demo1:
    # user: root                                  # 为了避免一些权限问题 在这我使用了root
    # restart: always                             # 重启方式
    # image: node:8.11.3                          # 指定服务所使用的镜像 在这里我选择了 LTS (长期支持)
    # container_name: node_demo_1                     # 容器名称
    ports:                                      # 对外暴露的端口定义
      - '8080:3001'
      - '8081:3001'
    build:
      context: "./"
      dockerfile: Dockerfile
    # volumes:
    #   - "~/index.js:/Users/web/Documents/workspace/indexTestDocker.js"
  # node_demo2:
  #   image: node:8.11.3                          # 指定服务所使用的镜像 在这里我选择了 LTS (长期支持)
  #   container_name: node_demo_2                 # 容器名称
  #   ports:                                      # 对外暴露的端口定义
  #     - '8081:3002'
